"""
swing_signals.py

Swing trading signal generator for NSE stocks.

Two-layer approach:
  1. Rule-based signals  — RSI, MACD, EMA crossover, Bollinger Bands, OBV
     (fast, interpretable, works without enough data to train a model)
  2. XGBoost model       — trained on those same indicators with a 5-day
     forward-return target; adds a probability score to each signal

Output per stock:
  - Signal: BUY / SELL / HOLD
  - Entry price, ATR-based stop loss, target (2:1 R:R)
  - Rule score and XGBoost confidence %
  - Reasoning bullets

⚠️  DISCLAIMER: Signals are generated by algorithms for EDUCATIONAL PURPOSES
    ONLY. This is NOT financial advice. Past signals do not guarantee future
    returns. Always do your own research and consult a SEBI-registered
    investment advisor before making any trading decisions.

Install:
    pip install -r requirements.txt

Run:
    python swing_signals.py
"""

from datetime import date, timedelta
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from stock_fetcher import fetch_historical_data


# ---------------------------------------------------------------------------
# Technical indicator calculations (pure pandas — no extra TA library needed)
# ---------------------------------------------------------------------------

def _rsi(close: pd.Series, period: int = 14) -> pd.Series:
    delta    = close.diff()
    gain     = delta.clip(lower=0)
    loss     = (-delta).clip(lower=0)
    avg_gain = gain.ewm(com=period - 1, min_periods=period).mean()
    avg_loss = loss.ewm(com=period - 1, min_periods=period).mean()
    rs       = avg_gain / avg_loss.replace(0, np.nan)
    return 100 - (100 / (1 + rs))


def _macd(close: pd.Series, fast=12, slow=26, signal=9):
    ema_fast    = close.ewm(span=fast,   adjust=False).mean()
    ema_slow    = close.ewm(span=slow,   adjust=False).mean()
    macd_line   = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    histogram   = macd_line - signal_line
    return macd_line, signal_line, histogram


def _bollinger(close: pd.Series, period=20, n_std=2):
    sma    = close.rolling(period).mean()
    std    = close.rolling(period).std()
    upper  = sma + n_std * std
    lower  = sma - n_std * std
    # BB position: 0 = at lower band, 1 = at upper band
    bb_pos = (close - lower) / (upper - lower).replace(0, np.nan)
    return upper, sma, lower, bb_pos


def _atr(high: pd.Series, low: pd.Series, close: pd.Series, period=14) -> pd.Series:
    tr = pd.concat([
        high - low,
        (high - close.shift()).abs(),
        (low  - close.shift()).abs(),
    ], axis=1).max(axis=1)
    return tr.ewm(span=period, adjust=False).mean()


def _obv(close: pd.Series, volume: pd.Series) -> pd.Series:
    direction = np.sign(close.diff()).fillna(0)
    return (direction * volume).cumsum()


def compute_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Append all technical indicators to the OHLCV DataFrame."""
    df = df.copy()

    # Trend EMAs
    df["EMA9"]  = df["Close"].ewm(span=9,  adjust=False).mean()
    df["EMA21"] = df["Close"].ewm(span=21, adjust=False).mean()
    df["EMA50"] = df["Close"].ewm(span=50, adjust=False).mean()

    # Momentum
    df["RSI"] = _rsi(df["Close"])
    df["MACD"], df["MACD_Signal"], df["MACD_Hist"] = _macd(df["Close"])

    # Volatility / band
    df["BB_Upper"], df["BB_Mid"], df["BB_Lower"], df["BB_Pos"] = _bollinger(df["Close"])
    df["ATR"] = _atr(df["High"], df["Low"], df["Close"])

    # Volume
    df["OBV"]     = _obv(df["Close"], df["Volume"])
    df["OBV_EMA"] = df["OBV"].ewm(span=21, adjust=False).mean()

    # Derived ratios used as ML features
    df["EMA_ratio"] = df["EMA9"] / df["EMA21"]
    df["ATR_pct"]   = df["ATR"]  / df["Close"]
    df["OBV_ratio"] = df["OBV"]  / df["OBV_EMA"].replace(0, np.nan)

    return df.dropna()


# ---------------------------------------------------------------------------
# Rule-based signal  (max score = +6 / min = -6)
# ---------------------------------------------------------------------------

def _rule_signal(row: pd.Series) -> tuple[str, int, list[str]]:
    """
    Score each indicator independently.  +1 = bullish, -1 = bearish.
    Final: score ≥ 3 → BUY,  score ≤ -3 → SELL,  else HOLD.
    """
    score   = 0
    reasons = []

    # 1. Long-term trend — price vs EMA50
    if row["Close"] > row["EMA50"]:
        score += 1
        reasons.append("Price above EMA50  (long-term uptrend)")
    else:
        score -= 1
        reasons.append("Price below EMA50  (long-term downtrend)")

    # 2. Short-term momentum — EMA9 / EMA21 crossover
    if row["EMA9"] > row["EMA21"]:
        score += 1
        reasons.append("EMA9 > EMA21  (short-term bullish crossover)")
    else:
        score -= 1
        reasons.append("EMA9 < EMA21  (short-term bearish crossover)")

    # 3. RSI — oversold/momentum zone = bullish, overbought = bearish
    rsi = row["RSI"]
    if rsi < 30:
        score += 1
        reasons.append(f"RSI {rsi:.1f} — oversold (reversal candidate)")
    elif 40 <= rsi <= 65:
        score += 1
        reasons.append(f"RSI {rsi:.1f} — healthy momentum zone")
    elif rsi > 70:
        score -= 1
        reasons.append(f"RSI {rsi:.1f} — overbought (caution)")
    else:
        reasons.append(f"RSI {rsi:.1f} — neutral")

    # 4. MACD — histogram direction
    if row["MACD"] > row["MACD_Signal"] and row["MACD_Hist"] > 0:
        score += 1
        reasons.append("MACD histogram positive  (bullish momentum)")
    elif row["MACD"] < row["MACD_Signal"] and row["MACD_Hist"] < 0:
        score -= 1
        reasons.append("MACD histogram negative  (bearish momentum)")
    else:
        reasons.append("MACD neutral / crossing")

    # 5. Bollinger Band position
    bp = row["BB_Pos"]
    if bp < 0.2:
        score += 1
        reasons.append(f"BB position {bp:.2f} — near lower band (mean-reversion entry)")
    elif bp > 0.8:
        score -= 1
        reasons.append(f"BB position {bp:.2f} — near upper band (stretched)")
    else:
        reasons.append(f"BB position {bp:.2f} — mid-range")

    # 6. OBV — volume confirms price direction?
    if row["OBV"] > row["OBV_EMA"]:
        score += 1
        reasons.append("OBV above its EMA  (buying pressure confirmed)")
    else:
        score -= 1
        reasons.append("OBV below its EMA  (selling pressure)")

    # Classify
    if score >= 3:
        signal = "BUY"
    elif score <= -3:
        signal = "SELL"
    else:
        signal = "HOLD"

    return signal, score, reasons


# ---------------------------------------------------------------------------
# XGBoost model — optional ML confidence layer
# ---------------------------------------------------------------------------

FEATURE_COLS = ["RSI", "MACD_Hist", "BB_Pos", "EMA_ratio", "ATR_pct", "OBV_ratio"]
FORWARD_DAYS = 5     # predict 5-trading-day return
THRESHOLD    = 0.02  # ≥2% up = BUY candidate, ≤-2% down = SELL candidate


def _make_labels(df: pd.DataFrame) -> pd.DataFrame:
    """Add a 5-day forward return label: 2=BUY, 1=HOLD, 0=SELL."""
    df = df.copy()
    df["fwd_return"] = df["Close"].pct_change(FORWARD_DAYS).shift(-FORWARD_DAYS)
    df["label"] = 1  # HOLD
    df.loc[df["fwd_return"] >= THRESHOLD, "label"]  = 2  # BUY
    df.loc[df["fwd_return"] <= -THRESHOLD, "label"] = 0  # SELL
    return df.dropna(subset=FEATURE_COLS + ["label"])


def train_xgb(df: pd.DataFrame):
    """
    Train an XGBoost classifier on historical indicator data.

    Uses TimeSeriesSplit so future data never leaks into training.
    Returns (model, accuracy_on_last_fold).
    """
    try:
        from xgboost import XGBClassifier
        from sklearn.model_selection import TimeSeriesSplit
        from sklearn.metrics import accuracy_score
    except ImportError:
        return None, None

    df_labeled = _make_labels(df)
    if len(df_labeled) < 100:
        return None, None

    X = df_labeled[FEATURE_COLS].values
    y = df_labeled["label"].values

    tscv  = TimeSeriesSplit(n_splits=5)
    model = XGBClassifier(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        use_label_encoder=False,
        eval_metric="mlogloss",
        random_state=42,
        verbosity=0,
    )

    val_acc = []
    for train_idx, test_idx in tscv.split(X):
        model.fit(X[train_idx], y[train_idx])
        preds = model.predict(X[test_idx])
        val_acc.append(accuracy_score(y[test_idx], preds))

    # Final fit on all data
    model.fit(X, y)
    avg_acc = np.mean(val_acc)
    return model, avg_acc


def xgb_confidence(model, row: pd.Series) -> tuple[str, float]:
    """
    Return (predicted_signal, confidence_pct) from the trained model
    for a single row of indicator values.
    """
    if model is None:
        return "N/A", 0.0

    features = row[FEATURE_COLS].values.reshape(1, -1)
    label_map = {0: "SELL", 1: "HOLD", 2: "BUY"}

    proba  = model.predict_proba(features)[0]
    pred   = int(model.predict(features)[0])
    conf   = float(proba[pred]) * 100
    return label_map[pred], conf


# ---------------------------------------------------------------------------
# Main report
# ---------------------------------------------------------------------------

def swing_report(
    symbols: list[str],
    exchange: str = "NSE",
    lookback_days: int = 365,
) -> pd.DataFrame:
    """
    Fetch data for each symbol, compute indicators, generate rule-based
    signal, train XGBoost, and print a formatted swing trading report.

    Args:
        symbols:      List of NSE tickers, e.g. ["SBIN", "HDFCBANK"].
        exchange:     "NSE" or "BSE".
        lookback_days: How many calendar days of history to fetch.
                       More = better XGBoost training. Minimum ~120.

    Returns:
        Summary DataFrame with one row per symbol.
    """
    today     = date.today()
    from_date = today - timedelta(days=lookback_days)

    print("=" * 68)
    print("  SWING TRADING SIGNAL REPORT  —  NSE Equities")
    print(f"  Generated : {today}     Lookback : {lookback_days} days")
    print("=" * 68)

    summary = []

    for symbol in symbols:
        print(f"\n{'─' * 68}")
        print(f"  {symbol}")
        print(f"{'─' * 68}")

        # 1. Fetch data
        df = fetch_historical_data(
            symbol=symbol,
            from_date=from_date,
            to_date=today,
            interval="ONE_DAY",
            exchange=exchange,
        )
        if df is None or len(df) < 60:
            print(f"  [SKIP] Not enough data (need ≥60 rows, got {len(df) if df is not None else 0})")
            continue

        # 2. Compute indicators
        df = compute_indicators(df)
        if df.empty:
            print("  [SKIP] Indicator computation returned empty DataFrame.")
            continue

        latest = df.iloc[-1]
        price  = latest["Close"]

        # 3. Rule-based signal
        rule_signal, rule_score, reasons = _rule_signal(latest)

        # 4. XGBoost signal
        model, val_acc = train_xgb(df)
        ml_signal, ml_conf = xgb_confidence(model, latest)

        # 5. ATR-based stop loss & target (2:1 risk-reward)
        atr = latest["ATR"]
        if rule_signal == "BUY":
            stop_loss = round(price - 1.5 * atr, 2)
            target    = round(price + 3.0 * atr, 2)
        elif rule_signal == "SELL":
            stop_loss = round(price + 1.5 * atr, 2)
            target    = round(price - 3.0 * atr, 2)
        else:
            stop_loss = target = None

        # 6. Print detail block
        print(f"  Price     : ₹{price:.2f}")
        print(f"  Signal    : {rule_signal:4s}  (rule score {rule_score:+d}/6)")
        print(f"  ML Signal : {ml_signal}  (XGBoost confidence {ml_conf:.1f}%"
              + (f",  val accuracy {val_acc*100:.1f}%" if val_acc else "") + ")")
        print(f"  RSI       : {latest['RSI']:.1f}   "
              f"MACD hist: {latest['MACD_Hist']:.3f}   "
              f"BB pos: {latest['BB_Pos']:.2f}   "
              f"ATR: ₹{atr:.2f}")
        if stop_loss:
            rr = abs(target - price) / abs(stop_loss - price)
            print(f"  Stop Loss : ₹{stop_loss}   Target: ₹{target}   R:R ≈ 1:{rr:.1f}")
        print("  Reasons:")
        for r in reasons:
            print(f"    • {r}")

        summary.append({
            "Symbol":        symbol,
            "Price (₹)":    round(price, 2),
            "Signal":        rule_signal,
            "Rule score":    f"{rule_score:+d}/6",
            "ML signal":     ml_signal,
            "ML conf %":     f"{ml_conf:.1f}",
            "RSI":           round(latest["RSI"], 1),
            "Stop Loss (₹)": stop_loss,
            "Target (₹)":   target,
        })

    # 7. Summary table
    print(f"\n{'=' * 68}")
    print("  SUMMARY TABLE")
    print("=" * 68)
    df_summary = pd.DataFrame(summary)
    if not df_summary.empty:
        print(df_summary.to_string(index=False))
    else:
        print("  No signals generated.")

    print("""
⚠️  DISCLAIMER
    These signals are generated by technical analysis algorithms for
    EDUCATIONAL PURPOSES ONLY and do NOT constitute financial advice.
    Past signals are no guarantee of future results. Swing trading
    carries significant risk of loss. Always conduct your own research
    and consult a SEBI-registered investment advisor before trading.
""")
    return df_summary


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    WATCHLIST = [
        "SBIN",
        "HDFCBANK",
        "RELIANCE",
        "TCS",
        "INFY",
        "ICICIBANK",
        "WIPRO",
        "AXISBANK",
    ]

    # 365 days → enough history for XGBoost training + reliable indicators
    df_result = swing_report(WATCHLIST, exchange="NSE", lookback_days=365)

    # Save the summary to CSV for later reference
    if not df_result.empty:
        out = f"swing_signals_{date.today()}.csv"
        df_result.to_csv(out, index=False)
        print(f"[INFO] Summary saved to '{out}'.")
